services: 
  db: 
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: my_db 
      MYSQL_ROOT_PASSWORD: password 
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 

  app:
    build: .
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
    command: node index.js
    ports: 
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: my_db 
      PORT: 3000
    depends_on:
      - db 

volumes:
  db_data:
  backend_node_modules:
